/*
 * generated by Xtext 2.10.0
 */
package javamm.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class JavammWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public JavammWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
