sudo: false

language: java

jdk: oraclejdk7

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

addons:
  apt:
    packages:
    - metacity

#before_install:
# - sudo apt-get update
# - sudo apt-get install gnome-themes-standard
# - sudo apt-get install metacity
# - sudo apt-get install libwebkit-dev
before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc

before_script:
 - sh -e /etc/init.d/xvfb start
 - metacity --sm-disable --replace 2> metacity.err &
 
script:
 - export
 - mvn -X -f javamm.releng/pom.xml clean verify -U -Dfindbugs.skip=true -Pide-tests