sudo: false

language: java

matrix:
  fast_finish: true
  include:
    # always build this environment
    - os: linux
      jdk: oraclejdk8
      env: DISPLAY=:99.0 ADDITIONAL="-Pjacoco-report coveralls:report"
    # only on PR
    - os: osx
      # default: osx_image: xcode8
      if: type IN (pull_request)

cache:
  directories:
  - $HOME/.m2

install: true

addons:
  apt:
    packages:
    - metacity

#before_install:
# - sudo apt-get update
# - sudo apt-get install gnome-themes-standard
# - sudo apt-get install metacity
# - sudo apt-get install libwebkit-dev
before_install:
 - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
 - echo $JAVA_HOME

before_script:
 - bash -e ./before_script.sh
 
script:
 - export
 - bash -e ./travis_build.sh

after_success:
 - ls -lR javamm.site/target/repository/

after_failure:
 - ls -lR javamm.swtbot.tests/target/work/
