/*
 * generated by Xtext 2.25.0
 */
package javamm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JavammStandaloneSetup extends JavammStandaloneSetupGenerated {

	public static void doSetup() {
		new JavammStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
