/*
* generated by Xtext
*/
package javamm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JavammStandaloneSetup extends JavammStandaloneSetupGenerated{

	public static void doSetup() {
		new JavammStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

