/**
 * generated by Xtext
 */
package javamm.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
public class JavammDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
