<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javamm" nsURI="http://www.Javamm.javamm" nsPrefix="javamm">
  <eClassifiers xsi:type="ecore:EClass" name="JavammProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importSection" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xtype.ecore#//XImportSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javammMethods" upperBound="-1"
        eType="#//JavammMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//JavammJvmFormalParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammJvmFormalParameter" eSuperTypes="../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammXAssignment" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XAssignment #//JavammArrayAccess"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammXVariableDeclaration" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalVariables" upperBound="-1"
        eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammAdditionalXVariableDeclaration"
      eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammArrayAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammXMemberFeatureCall" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XMemberFeatureCall #//JavammArrayAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayAccessExpression"
        eType="#//JavammArrayAccessExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammArrayConstructorCall" eSuperTypes="#//JavammArrayAccess ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//JavammArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayLiteral" eType="#//JavammArrayLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammArrayDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openBracket" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammArrayLiteral" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XListLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammArrayAccessExpression" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression #//JavammArrayAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammBranchingStatement" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instruction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavammContinueStatement" eSuperTypes="#//JavammBranchingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammBreakStatement" eSuperTypes="#//JavammBranchingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammCharLiteral" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XStringLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammPrefixOperation" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XPostfixOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammConditionalExpression" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XIfExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavammSwitchStatements" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"/>
</ecore:EPackage>
