/*
 * generated by Xtext
 */
package javamm.serializer;

import javamm.internal.serializer.XbaseSemanticSequencerAccess;

/**
 * Customized to deal with custom rules from Xbase.
 * 
 * @author Lorenzo Bettini
 *
 */
public class JavammSemanticSequencer extends XbaseSemanticSequencerAccess {

}
