/*
 * generated by Xtext
 */
package javamm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JavammUiModule extends javamm.ui.AbstractJavammUiModule {
	public JavammUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
