/**
 * generated by Xtext
 */
package javamm.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * @author Lorenzo Bettini
 */
public class JavammProposalProvider extends AbstractJavammProposalProvider {
	@Override
	public void completeMain_Expressions(final EObject model, final Assignment assignment,
			final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
		this.completeWithinBlock(model, context, acceptor);
	}
}
