/*
 * generated by Xtext 2.11.0
 */
package javamm.ide

import com.google.inject.Guice
import javamm.JavammRuntimeModule
import javamm.JavammStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class JavammIdeSetup extends JavammStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new JavammRuntimeModule, new JavammIdeModule))
	}
	
}
