/*
 * generated by Xtext 2.25.0
 */
package javamm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import javamm.JavammRuntimeModule;
import javamm.JavammStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JavammIdeSetup extends JavammStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JavammRuntimeModule(), new JavammIdeModule()));
	}
	
}
