name: Java CI with Maven

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'

jobs:
  build:
    env:
       COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set Maven Additional Goals
      run: |
        echo "ADDITIONAL_GOALS=coveralls:report sonar:sonar" >> $GITHUB_ENV
      if: ${{ env.COVERALLS_REPO_TOKEN }}
    - name: Build with Maven
      run: >
        xvfb-run
        mvn -f javamm.parent/pom.xml
        verify -Pide-tests -Pjacoco
        -DrepoToken=$COVERALLS_REPO_TOKEN
        -DpullRequest=${{ github.event.pull_request.number }}
        -Dsonar.organization=lorenzobettini-github
        -Dsonar.host.url=https://sonarcloud.io
        $ADDITIONAL_GOALS
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: test-results-${{ runner.os }}
        path: '**/*.tests/target/surefire-reports'
